<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>

	<link name="thigh">
		<collision>
		  <origin rpy="0 0 0" xyz="0 0 0"/>
		  <geometry>
		   <mesh filename="package://robbie_description/meshes/THIGH_ASS_PART_collision.STL"/>
		 </geometry>
	 </collision>
	 <visual>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
		  <mesh filename="package://robbie_description/meshes/THIGH_ASS_PART.STL" scale="1 1 1"/>
		</geometry>
		<material name="black">
		  <color rgba="0.0 0.0 0.0 1.0"/>
		</material>
	</visual>
	<inertial>
		<origin xyz="0 0 ${thighHeight/2}" rpy="0 0 0"/>
		<mass value="${thighMass}"/>
		<box_inertia m="${thighMass}" x="${thighWidth}" y="${thighDepth}" z="${thighHeight}"/>
	</inertial>
	</link>

</robot>








